### ISSUE TITLE
Themes don't change 

### ISSUE THREAD

**Issue by BotAn14XD** [notmike101/betterdiscord-server-themes#3]
I have an issue
Today plugin stopped working
Even with enabled and setted up plugin, it just didn't change themes. 
Video: [here](https://www.youtube.com/watch?v=HC9O2w5g_Mo)

I have another issue with bd, so it's maybe better discord troubles or I don't know

Hope it will be fixed somehow soon. This plugin is one of the best <3

**Comment by WatanabeDaiki135** [comment]
same here

**Comment by notmike101** [comment]
I'll take a look at this tonight and see what's going on.

**Comment by notmike101** [comment]
@BotAn14XD If you'd like, go ahead and test [this version](https://raw.githubusercontent.com/notmike101/betterdiscord-server-themes/release/serverthemes.plugin.js)

It's working on my end and through all my tests.

**Comment by BotAn14XD** [comment]
> @BotAn14XD If you'd like, go ahead and test [this version](https://raw.githubusercontent.com/notmike101/betterdiscord-server-themes/release/serverthemes.plugin.js)
> 
> It's working on my end and through all my tests.

It works! 
Thank you a lot!

**Comment by WatanabeDaiki135** [comment]
Oh my, It works, thanks <3
