### ISSUE TITLE
Feature request: Blacklist themes

### ISSUE THREAD

**Issue by BatEagles** [notmike101/betterdiscord-server-themes#4]
A feature I would love to see is the ability to blacklist certain themes so that they don't get turned off when switching servers. For instance the Radial Styles theme isn't a full theme, it only changes one element, but I would like it to stay on no matter which server I'm in.

**Comment by notmike101** [comment]
Not sure of the best way to implement this, let me think on it for a bit and come back to this later.

**Comment by notmike101** [comment]
Coming back to this, I don't think that the plugin should handle that since that seems like it would be more of a theme issue resolved by combining themes.

If you want to use multiple theme fragments at the same time, make a theme containing those fragments.
